#!/bin/bash

# Build docker image
git clone https://github.com/fermuch/dokku-pgis-dockerfiles.git /tmp/dokku-pgis-dockerfiles
docker build -q=true -t kloadut/postgres /tmp/dokku-pgis-dockerfiles
rm -rf /tmp/dokku-pgis-dockerfiles
